### ISSUE TITLE
Move configurations from secret to configMap

### ISSUE THREAD

**Issue by naveen-armedia** [ArkCase/ark_helm_charts#2]

**Comment by fabricetriboix** [comment]
@naveen-armedia There is a long thread on this issue in the PR. I don't understand what I can do about it. As far as I can see, what you are asking is not possible. Regarding the expansion of environment variables in the ActiveMQ/Java configuration files, please provide me with some documentation on how to do that, if that's what you have in mind.

**Comment by naveen-armedia** [comment]
@fabricetriboix It is a workaround that I suggested when we need to use environment variables in the configuration files. I gave you examples in the closed PR about using configs in configMap and secrets in the secret objects. We can discuss this in a meeting if you want.

**Comment by fabricetriboix** [comment]
@naveen-armedia I have enough of discussions. If you want me to effect the change you request from me, I would require from you that you provide me with accurate information in response to my questions, which I believe are precise and unambiguous. Thank you for your understanding.

**Comment by naveen-armedia** [comment]
@fabricetriboix As i said earlier this task could be taken up in later part of development that is why i kept this as enhancement.  I will provide you proper examples with CloudConfig and Pentaho-ce helm charts when its PR comes. Thanks!!
